### ISSUE TITLE
Generating patches of source domain data. 

### ISSUE THREAD

**Issue by TaiToTo** [dliu5812/PDAM#1]
Thank you for sharing the codes of this pioneering UDA instance segmentation. 

To make 10K patches of BBC039V1 images, which did you use for training?
Or could you share the codes which you used for data generating those train datasets, besides their corresponding annotations as json files?

**Comment by dliu5812** [comment]
Hi,

Sorry for the late reply. As mentioned in the e-mail reply to you, I will find some time to polish the data augmentation code by improving the readability, and publish them on GitHub as well.

For the data synthesis code, I just use the official CycleGAN repository, as mentioned in the readme file.
