### ISSUE TITLE
The sizes of images used in training and inferences.

### ISSUE THREAD

**Issue by TaiToTo** [dliu5812/PDAM#3]
How can I avoid inferences like below?

I tired to check if my network was properly trained by inferring the 256*256 batches from the source domain which I used during training. 
But I got the bonding box detection results as below for each a 256*256 training patch and a 1000*1000 test image. 

I think Mask R-CNN usually does not specify input image sizes. 
I bet I did something wrong in configuration. 
![3039_img](https://user-images.githubusercontent.com/52999158/123741855-b9b9bd00-d8e5-11eb-8a3b-9859e2c09da7.png)
![prostate_1](https://user-images.githubusercontent.com/52999158/123742101-1cab5400-d8e6-11eb-89ec-a22c56f05abc.png)

**Comment by dliu5812** [comment]
Hi, 

For the two predictions you showed, I think they were from the inference code 'fluo2tcga_infer.py' with the config file 'e2e_mask_rcnn_R_101_FPN_1x_gn_fluo2tcga.yaml'. 

Have you changed any default settings in these two files except for the image path?
